import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { getStatus, type Phase } from './status.js';
import { listRfcs } from './rfc.js';
import { listInvestigations } from './investigate.js';
import { PHASE_ORDER, PHASE_LABELS } from './utils.js';

export interface BriefResult {
    generated: boolean;
    outputPath: string;
    content: string;
    stats: {
        techInvariants: number;
        uxInvariants: number;
        openItems: number;
        totalLines: number;
    };
    error?: string;
}

interface InvariantEntry {
    id: string;
    statement: string;
}

function extractInvariantOneLiner(content: string, prefix: string): InvariantEntry[] {
    const entries: InvariantEntry[] = [];
    const regex = new RegExp(`^## (${prefix}\\d+):\\s*(.+)`, 'gm');
    let match: RegExpExecArray | null;

    while ((match = regex.exec(content)) !== null) {
        const id = match[1]!;
        // Try to get STATEMENT field first for a cleaner one-liner
        const start = match.index;
        const rest = content.slice(start);
        const nextSection = rest.indexOf('\n## ', 3);
        const section = nextSection > 0 ? rest.slice(0, nextSection) : rest;
        const stmtMatch = section.match(/STATEMENT:\s*(.+)/);
        const statement = stmtMatch ? stmtMatch[1]!.trim() : match[2]!.trim();
        entries.push({ id, statement });
    }

    return entries;
}

function listEscalations(cwd: string): { id: string; title: string; status: string }[] {
    const escalationsDir = join(cwd, '.devkit', 'qa', 'escalations');
    if (!existsSync(escalationsDir)) return [];

    return readdirSync(escalationsDir)
        .filter(f => f.startsWith('ESC-') && f.endsWith('.md'))
        .sort()
        .map(f => {
            const content = readFileSync(join(escalationsDir, f), 'utf-8');
            const titleMatch = content.match(/^# (.+)/m);
            const statusMatch = content.match(/^STATUS:\s*(.+)/m);
            return {
                id: f.replace('.md', ''),
                title: titleMatch?.[1] ?? f,
                status: statusMatch?.[1]?.trim() ?? 'unknown',
            };
        });
}

function detectProjectStructure(cwd: string): string[] {
    const lines: string[] = [];
    try {
        const entries = readdirSync(cwd, { withFileTypes: true });

        // Known DevKit dirs with descriptions
        const descriptions: Record<string, string> = {
            'cli': 'CLI source (TypeScript)',
            '.devkit': 'DevKit artifacts',
            '.specify': 'spec-kit workspace',
            '.agent': 'Agent Skills',
            '.claude': 'Claude agent config',
            '.gemini': 'Gemini agent config',
            'src': 'Source code',
            'tests': 'Tests',
            'docs': 'Documentation',
            'dist': 'Build output',
            'node_modules': 'Dependencies',
        };

        for (const entry of entries) {
            if (!entry.isDirectory()) continue;
            if (entry.name.startsWith('.git') && entry.name !== '.gitignore') continue;
            if (entry.name === 'node_modules') continue;
            if (entry.name === '.snapshots') continue;

            const desc = descriptions[entry.name];
            if (desc) {
                lines.push(`  ${entry.name.padEnd(14)} — ${desc}`);
            } else {
                lines.push(`  ${entry.name}/`);
            }
        }
    } catch { /* ignore */ }
    return lines;
}

function detectDevCommands(cwd: string): string[] {
    const lines: string[] = [];
    const pkgPath = join(cwd, 'package.json');

    if (existsSync(pkgPath)) {
        try {
            const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
            if (pkg.scripts) {
                for (const [name, cmd] of Object.entries(pkg.scripts)) {
                    lines.push(`  npm run ${name.padEnd(12)} — ${cmd}`);
                }
            }
        } catch { /* ignore */ }
    }

    return lines;
}

export function generateBrief(cwd: string): BriefResult {
    const devkitDir = join(cwd, '.devkit');
    const outputPath = join(devkitDir, 'BRIEF.md');

    if (!existsSync(devkitDir)) {
        return {
            generated: false,
            outputPath,
            content: '',
            stats: { techInvariants: 0, uxInvariants: 0, openItems: 0, totalLines: 0 },
            error: '.devkit/ not found. Run "devkit init" first.',
        };
    }

    const lines: string[] = [];
    const now = new Date().toISOString().split('T')[0];

    // ── Header ──
    lines.push('# Project Brief');
    lines.push(`> Auto-generated by \`devkit brief\`. Last updated: ${now}`);
    lines.push('> For details on any item, see the referenced file.');
    lines.push('');

    // ── Phase & Progress ──
    const status = getStatus(cwd);
    if (status) {
        const phaseIdx = PHASE_ORDER.indexOf(status.phase) + 1;
        lines.push(`## Phase: ${PHASE_LABELS[status.phase]} (${phaseIdx}/${PHASE_ORDER.length})`);
        lines.push('');

        for (const phase of PHASE_ORDER) {
            const s = status.phaseProgress[phase];
            const icon = s === 'done' ? '✅' : s === 'in_progress' ? '🔄' : '⬜';
            const pointer = phase === status.phase ? ' ◀ current' : '';
            lines.push(`  ${icon} ${PHASE_LABELS[phase]}${pointer}`);
        }
        lines.push('');
    }

    // ── Invariants ──
    const archInvariantsPath = join(devkitDir, 'arch', 'invariants.md');
    const uxInvariantsPath = join(devkitDir, 'product', 'ux_invariants.md');

    const techInvariants = existsSync(archInvariantsPath)
        ? extractInvariantOneLiner(readFileSync(archInvariantsPath, 'utf-8'), 'I')
        : [];
    const uxInvariants = existsSync(uxInvariantsPath)
        ? extractInvariantOneLiner(readFileSync(uxInvariantsPath, 'utf-8'), 'U')
        : [];

    if (techInvariants.length > 0 || uxInvariants.length > 0) {
        lines.push('## Invariants');
        lines.push('');

        if (techInvariants.length > 0) {
            lines.push('### Technical');
            for (const inv of techInvariants) {
                lines.push(`  - ${inv.id}: ${inv.statement}`);
            }
            lines.push('');
        }

        if (uxInvariants.length > 0) {
            lines.push('### UX');
            for (const inv of uxInvariants) {
                lines.push(`  - ${inv.id}: ${inv.statement}`);
            }
            lines.push('');
        }
    }

    // ── Open Items ──
    const rfcs = listRfcs(cwd);
    const investigations = listInvestigations(cwd);
    const escalations = listEscalations(cwd);

    const openRfcs = rfcs.filter(r => r.status === 'open');
    const openInvs = investigations.filter(i => i.status === 'open');
    const openEscs = escalations.filter(e => e.status === 'open');
    const totalOpen = openRfcs.length + openInvs.length + openEscs.length;

    if (totalOpen > 0) {
        lines.push('## Open Items');
        lines.push('');
        for (const r of openRfcs) {
            lines.push(`  - 📋 ${r.id}: ${r.title.replace(/^RFC-\d+:\s*/, '')} → .devkit/arch/decisions/${r.id}.md`);
        }
        for (const i of openInvs) {
            lines.push(`  - 🔬 ${i.id}: ${i.title.replace(/^INV-\d+:\s*/, '')} → .devkit/arch/decisions/${i.id}.md`);
        }
        for (const e of openEscs) {
            lines.push(`  - 🚨 ${e.id}: ${e.title.replace(/^ESC-\d+:\s*/, '')} → .devkit/qa/escalations/${e.id}.md`);
        }
        lines.push('');
    }

    // ── Resolved Decisions (recent, max 5) ──
    const resolvedRfcs = rfcs.filter(r => r.status === 'accepted').slice(-5);
    const resolvedInvs = investigations.filter(i => i.status === 'resolved').slice(-5);

    if (resolvedRfcs.length > 0 || resolvedInvs.length > 0) {
        lines.push('## Recent Decisions');
        lines.push('');
        for (const r of resolvedRfcs) {
            lines.push(`  - ✅ ${r.id}: ${r.title.replace(/^RFC-\d+:\s*/, '')} [accepted]`);
        }
        for (const i of resolvedInvs) {
            lines.push(`  - ✅ ${i.id}: ${i.title.replace(/^INV-\d+:\s*/, '')} [resolved]`);
        }
        lines.push('');
    }

    // ── Project Structure ──
    const structureLines = detectProjectStructure(cwd);
    if (structureLines.length > 0) {
        lines.push('## Project Structure');
        lines.push('');
        lines.push(...structureLines);
        lines.push('');
    }

    // ── Dev Commands ──
    const devCmdLines = detectDevCommands(cwd);
    if (devCmdLines.length > 0) {
        lines.push('## Dev Commands');
        lines.push('');
        lines.push(...devCmdLines);
        lines.push('');
    }

    // ── DevKit Commands ──
    lines.push('## DevKit Commands');
    lines.push('');
    lines.push('  devkit status    — Current phase and progress');
    lines.push('  devkit validate  — Check artifact correctness');
    lines.push('  devkit gate      — Check phase transition');
    lines.push('  devkit advance   — Move to next phase');
    lines.push('  devkit impact    — Analyze change impact');
    lines.push('  devkit coverage  — Invariant test coverage');
    lines.push('  devkit brief     — Regenerate this file');
    lines.push('');

    const content = lines.join('\n');

    // Write file
    writeFileSync(outputPath, content, 'utf-8');

    return {
        generated: true,
        outputPath,
        content,
        stats: {
            techInvariants: techInvariants.length,
            uxInvariants: uxInvariants.length,
            openItems: totalOpen,
            totalLines: lines.length,
        },
    };
}
